services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
