version: "3.8"

services:
  frontend:
    container_name: hims-frontend
    ports:
      - target: ${FRONTEND_PORT}
        published: ${FRONTEND_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    image: ghcr.io/himmelforce/hims-frontend:latest
    env_file:
      - .env
      - .env.data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}/"]
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 100s
    depends_on:
      api:
        condition: service_healthy
    networks:
      - default

  api:
    container_name: hims-api
    ports:
      - target: ${API_PORT}
        published: ${API_PORT}
    env_file:
      - .env
      - .env.data
    image: ghcr.io/himmelforce/hims-api:latest
    volumes:
      - ./uploads:/usr/src/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/"]
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 100s
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default

  mongo:
    image: mongo
    container_name: hims-mongo
    ports:
      - target: ${MONGO_PORT}
        published: ${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - default

  redis:
    image: redis
    container_name: hims-redis
    ports:
      - target: ${REDIS_PORT}
        published: ${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - default

  nginx:
    container_name: hims-nginx
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    image: ghcr.io/himmelforce/hims-nginx:latest
    env_file:
      - .env
      - .env.data
    volumes:
      - /etc/letsencrypt/live/${HOST}/fullchain.pem:/etc/letsencrypt/live/${HOST}/fullchain.pem:ro
      - /etc/letsencrypt/live/${HOST}/privkey.pem:/etc/letsencrypt/live/${HOST}/privkey.pem:ro
    networks:
      - default
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  mongo-data:
    driver: local
  uploads:
    driver: local

networks:
  default:
