FROM node:20.9.0-alpine

RUN apk update && apk add --no-cache curl

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i --verbose

COPY . .

ARG FRONTEND_SERVICE_PORT
EXPOSE ${FRONTEND_SERVICE_PORT}

CMD ["npm", "run", "start:development"]
